#!/usr/bin/env python3
"""Generate the test summary report and refresh the README results table.

Usage (no arguments, run from anywhere):

    python scripts/generate_summary.py

Inputs:
    test-cases/test_cases.csv   executed test results (Actual_Result, Status, ...)
    bug-reports/bugs.csv        logged defects

Outputs:
    reports/test-summary.md               full summary report
    README.md between <!-- SUMMARY:START --> and <!-- SUMMARY:END -->
                                          compact results table

Rules applied:
    * Status values are Pass / Fail / Blocked / Not Run.
      An empty (not yet executed) Status counts as "Not Run".
    * The pass percentage is computed ONLY from executed cases
      (Pass + Fail + Blocked); with zero executed cases it is reported
      as "N/A" instead of a misleading 0%.
    * Empty or missing data never crashes the script: counts stay at 0
      and the report says so.
    * Nothing is invented: the "Key Findings" section always carries a
      [TODO] placeholder for the author's own words.

Only the Python standard library is used.
"""

import csv
import sys
from pathlib import Path

# Repo root = parent of the scripts/ folder that contains this file.
ROOT = Path(__file__).resolve().parent.parent
TEST_CASES_CSV = ROOT / "test-cases" / "test_cases.csv"
BUGS_CSV = ROOT / "bug-reports" / "bugs.csv"
README = ROOT / "README.md"
OUT_REPORT = ROOT / "reports" / "test-summary.md"

MARKER_START = "<!-- SUMMARY:START -->"
MARKER_END = "<!-- SUMMARY:END -->"

# The four status buckets, in report order.
STATUSES = ("Pass", "Fail", "Blocked", "Not Run")


def read_csv(path):
    """Read a CSV into a list of dicts; missing file or bad rows -> []."""
    if not path.is_file():
        print("WARNING: %s not found - treating as empty." % path.name)
        return []
    try:
        with path.open(newline="", encoding="utf-8-sig") as handle:
            reader = csv.DictReader(handle)
            if not reader.fieldnames:
                return []
            return [dict(row) for row in reader]
    except (csv.Error, OSError) as exc:
        print("WARNING: could not read %s (%s) - treating as empty."
              % (path.name, exc))
        return []


def normalize_status(row):
    """Map a Status cell to one of the four buckets (empty -> Not Run)."""
    raw = (row.get("Status") or "").strip()
    if not raw:
        return "Not Run"
    for status in STATUSES:
        if raw.lower() == status.lower():
            return status
    # Unknown wording: treat as Not Run but keep it honest in the notes.
    return "Not Run"


def summarize_tests(test_rows):
    """Aggregate test-case counts overall and per module."""
    by_status = dict((s, 0) for s in STATUSES)
    modules = []          # modules in first-appearance order
    by_module = {}        # module -> status counts

    for row in test_rows:
        status = normalize_status(row)
        by_status[status] += 1

        module = (row.get("Module") or "Uncategorised").strip() \
            or "Uncategorised"
        if module not in by_module:
            modules.append(module)
            by_module[module] = dict((s, 0) for s in STATUSES)
        by_module[module][status] += 1

    executed = by_status["Pass"] + by_status["Fail"] + by_status["Blocked"]
    if executed > 0:
        pass_pct = "%.1f%%" % (100.0 * by_status["Pass"] / executed)
    else:
        pass_pct = "N/A"

    return {
        "total": len(test_rows),
        "by_status": by_status,
        "executed": executed,
        "pass_pct": pass_pct,
        "modules": modules,
        "by_module": by_module,
    }


def summarize_bugs(bug_rows):
    """Count logged defects by severity (preserving a fixed order)."""
    order = ("Critical", "High", "Medium", "Low")
    by_severity = dict((s, 0) for s in order)
    other = 0
    for row in bug_rows:
        sev = (row.get("Severity") or "").strip().title()
        if sev in by_severity:
            by_severity[sev] += 1
        else:
            other += 1
    return {"total": len(bug_rows), "by_severity": by_severity,
            "other": other}


def render_report(tests, bugs):
    """Render reports/test-summary.md as Markdown."""
    lines = ["# Test Summary Report", ""]
    lines.append("_Generated by `scripts/generate_summary.py` from "
                 "`test-cases/test_cases.csv` and `bug-reports/bugs.csv`. "
                 "Re-run the script after updating the CSVs._")
    lines.append("")

    # --- Overall totals -------------------------------------------------
    lines.append("## Overview")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append("| Total test cases | %d |" % tests["total"])
    for status in STATUSES:
        lines.append("| %s | %d |" % (status, tests["by_status"][status]))
    lines.append("| Executed (Pass+Fail+Blocked) | %d |" % tests["executed"])
    lines.append("| Pass %% (executed cases only) | %s |" % tests["pass_pct"])
    lines.append("| Defects logged | %d |" % bugs["total"])
    lines.append("")

    # --- Results by module ---------------------------------------------
    lines.append("## Results by Module")
    lines.append("")
    if tests["modules"]:
        lines.append("| Module | Total | Pass | Fail | Blocked | Not Run |")
        lines.append("|--------|------:|-----:|-----:|--------:|--------:|")
        for module in tests["modules"]:
            counts = tests["by_module"][module]
            total = sum(counts.values())
            lines.append("| %s | %d | %d | %d | %d | %d |"
                         % (module, total, counts["Pass"], counts["Fail"],
                            counts["Blocked"], counts["Not Run"]))
    else:
        lines.append("_No test cases found._")
    lines.append("")

    # --- Defects by severity -------------------------------------------
    lines.append("## Defects by Severity")
    lines.append("")
    if bugs["total"]:
        lines.append("| Severity | Count |")
        lines.append("|----------|------:|")
        for sev in ("Critical", "High", "Medium", "Low"):
            lines.append("| %s | %d |" % (sev, bugs["by_severity"][sev]))
        if bugs["other"]:
            lines.append("| Unspecified | %d |" % bugs["other"])
    else:
        lines.append("_No defects logged yet (bug-reports/bugs.csv is "
                     "header-only)._")
    lines.append("")

    # --- Key findings (author fills this in) ----------------------------
    lines.append("## Key Findings")
    lines.append("")
    lines.append("[TODO: write 3-5 findings in my own words]")
    lines.append("")

    return "\n".join(lines)


def render_readme_table(tests, bugs):
    """Render the compact table that goes between the README markers."""
    lines = ["| Total | Pass | Fail | Blocked | Not Run | Pass % "
             "(executed only) | Defects |",
             "|------:|-----:|-----:|--------:|--------:|"
             "------------------:|--------:|",
             "| %d | %d | %d | %d | %d | %s | %d |"
             % (tests["total"],
                tests["by_status"]["Pass"],
                tests["by_status"]["Fail"],
                tests["by_status"]["Blocked"],
                tests["by_status"]["Not Run"],
                tests["pass_pct"],
                bugs["total"])]
    return "\n".join(lines)


def update_readme(tests, bugs):
    """Replace content between the SUMMARY markers in README.md.

    Skips with a message when README.md does not exist yet or the
    markers are missing - never crashes.
    """
    if not README.is_file():
        print("README.md not found - skipping marker update.")
        return
    text = README.read_text(encoding="utf-8")
    start = text.find(MARKER_START)
    end = text.find(MARKER_END)
    if start == -1 or end == -1 or end < start:
        print("README.md has no SUMMARY:START/SUMMARY:END markers - "
              "skipping marker update.")
        return
    new_text = (
        text[: start + len(MARKER_START)]
        + "\n" + render_readme_table(tests, bugs) + "\n"
        + text[end:]
    )
    if new_text != text:
        README.write_text(new_text, encoding="utf-8")
        print("  updated results table in README.md")
    else:
        print("  README.md results table already up to date")


def main():
    """Read both CSVs, write the report, refresh the README markers."""
    test_rows = read_csv(TEST_CASES_CSV)
    bug_rows = read_csv(BUGS_CSV)

    tests = summarize_tests(test_rows)
    bugs = summarize_bugs(bug_rows)

    OUT_REPORT.parent.mkdir(parents=True, exist_ok=True)
    OUT_REPORT.write_text(render_report(tests, bugs), encoding="utf-8")
    print("  wrote %s" % OUT_REPORT.relative_to(ROOT))

    update_readme(tests, bugs)

    print("Done: %d test case(s), %d executed, pass rate %s, "
          "%d defect(s)." % (tests["total"], tests["executed"],
                             tests["pass_pct"], bugs["total"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
